"""Hardware-specific layout definitions."""

from calypso.hardware.atlas3 import (
    BoardProfile,
    CONNECTOR_MAP,
    ConnectorInfo,
    PROFILE_80,
    PROFILE_144,
    STATION_MAP,
    StationInfo,
    connector_for_port,
    get_board_profile,
    port_register_base,
    station_for_port,
    station_register_base,
)
from calypso.hardware.atlas3_phy import (
    PhyCmdStatusBits,
    PhyCmdStatusRegister,
    PortControlRegister,
    SerDesDiagnosticRegister,
    TestPatternRate,
    UTP_PRESET_NAMES,
    UTPTestResult,
    UserTestPattern,
    VendorPhyRegs,
    get_quad_diag_offset,
    get_utp_preset,
)
from calypso.hardware.pcie_registers import (
    AERCapability,
    CorrErrBits,
    ExtCapabilityID,
    PCIeCapability,
    PCIeCapabilityID,
    PCIeConfigSpace,
    PCIeLinkSpeed,
    PCIeLinkWidth,
    PhysLayer64GT,
    UncorrErrBits,
)

__all__ = [
    "AERCapability",
    "BoardProfile",
    "CONNECTOR_MAP",
    "ConnectorInfo",
    "CorrErrBits",
    "ExtCapabilityID",
    "PCIeCapability",
    "PCIeCapabilityID",
    "PCIeConfigSpace",
    "PCIeLinkSpeed",
    "PCIeLinkWidth",
    "PROFILE_80",
    "PROFILE_144",
    "PhyCmdStatusBits",
    "PhyCmdStatusRegister",
    "PhysLayer64GT",
    "PortControlRegister",
    "STATION_MAP",
    "SerDesDiagnosticRegister",
    "StationInfo",
    "TestPatternRate",
    "UTP_PRESET_NAMES",
    "UTPTestResult",
    "UncorrErrBits",
    "UserTestPattern",
    "VendorPhyRegs",
    "connector_for_port",
    "get_board_profile",
    "get_quad_diag_offset",
    "get_utp_preset",
    "port_register_base",
    "station_for_port",
    "station_register_base",
]
