"""Hardware-specific layout definitions."""

from calypso.hardware.atlas3 import (
    BoardProfile,
    CONNECTOR_MAP,
    ConnectorInfo,
    PROFILE_80,
    PROFILE_144,
    STATION_MAP,
    StationInfo,
    connector_for_port,
    get_board_profile,
    port_register_base,
    station_for_port,
)
from calypso.hardware.atlas3_phy import (
    PhyCmdStatusBits,
    PhyCmdStatusRegister,
    PortControlRegister,
    SerDesDiagnosticRegister,
    TestPatternRate,
    UTP_PRESET_NAMES,
    UTPTestResult,
    UserTestPattern,
    VendorPhyRegs,
    get_quad_diag_offset,
    get_utp_preset,
)

__all__ = [
    "BoardProfile",
    "CONNECTOR_MAP",
    "ConnectorInfo",
    "PROFILE_80",
    "PROFILE_144",
    "PhyCmdStatusBits",
    "PhyCmdStatusRegister",
    "PortControlRegister",
    "STATION_MAP",
    "SerDesDiagnosticRegister",
    "StationInfo",
    "TestPatternRate",
    "UTP_PRESET_NAMES",
    "UTPTestResult",
    "UserTestPattern",
    "VendorPhyRegs",
    "connector_for_port",
    "get_board_profile",
    "get_quad_diag_offset",
    "get_utp_preset",
    "port_register_base",
    "station_for_port",
]
